### ISSUE TITLE
Missing _utils files

### ISSUE THREAD

**Issue by OscarVsp** [leopardbyte/aram-bench-swap-pengu#1]
Very good idea for a plugin ! Unfortunalty I got this error while trying it

![image](https://github.com/leopardbyte/aram-bench-swap-pengu/assets/30955488/66a01060-c6ed-460b-bc56-3b45e33a766f)

I've downloaded the file from the discord `#plugin-releases` channel, extracted it then copied to the plugins folder.

When starting the client and looking at the console, there is a `ERR_FILE_NOT_FOUND` error from the firstline of `index.js`

**Comment by leopardbyte** [comment]
Hey,
I forgot to include the _utils file thats my fault 🌵 
added it here on github just download _utils.js and add it diretly to the plugins folder. Not in the same folder as the aram plugin and no seperate folder is needed just drag it in "\Pengu Loader\plugins".
should fix your issue

**Comment by OscarVsp** [comment]
Indeed working fine now, thanks !
